/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NapiRetrievalRequest {
  entityId: string
  queryText: string
  denseLimit: number
  limit: number
}
export interface NapiRecallSummary {
  content: string
  dateCreated: string
  entityFactId?: number
  factId?: number
}
export interface NapiRecallObject {
  id: number
  content: string
  rankScore?: number
  similarity?: number
  dateCreated?: string
  summaries?: Array<NapiRecallSummary>
}
export interface NapiMessage {
  role: string
  content: string
}
export interface NapiAugmentationInput {
  entityId: string
  processId?: string
  conversationId?: string
  conversationMessages?: Array<NapiMessage>
  systemPrompt?: string
  llmProvider?: string
  llmModel?: string
  llmProviderSdkVersion?: string
  framework?: string
  platformProvider?: string
  storageDialect?: string
  storageCockroachdb?: boolean
  sdkVersion?: string
  useMockResponse?: boolean
  sessionId?: string
  factId?: string
  content?: string
}
export interface NapiEmbeddingRow {
  id: number | string
  contentEmbedding: Float32Array
}
export interface NapiCandidateSummaryRow {
  content: string
  dateCreated: string
}
export interface NapiCandidateFactRow {
  id: number | string
  content: string
  dateCreated: string
  summaries?: Array<NapiCandidateSummaryRow>
}
export interface NapiWriteAck {
  writtenOps: number
}
export declare class MemoriEngine {
  constructor(modelName: string | undefined | null, fetchEmbeddingsCb: (id: number, reqJson: string) => void, fetchFactsByIdsCb: (id: number, reqJson: string) => void, writeBatchCb: (id: number, reqJson: string) => void)
  resolveEmbeddingsCallback(id: number, result: Array<NapiEmbeddingRow>): void
  resolveFactsCallback(id: number, result: Array<NapiCandidateFactRow>): void
  resolveWriteCallback(id: number, result: NapiWriteAck): void
  embedTexts(texts: Array<string>): Array<Float32Array>
  retrieve(request: NapiRetrievalRequest): Promise<Array<NapiRecallObject>>
  recall(request: NapiRetrievalRequest): Promise<string>
  submitAugmentation(input: NapiAugmentationInput): string
  waitForAugmentation(timeoutMs?: number | undefined | null): Promise<boolean>
  shutdown(): void
}
